apiVersion: v1
kind: Service
metadata:
  name: {{ include "omniprice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8120
      protocol: TCP
      name: http
  selector:
    {{- include "omniprice.selectorLabels" . | nindent 4 }}
