
replicaCount: 1

image:
  repository: osmslwc.azurecr.io/omniprice:example
  pullPolicy: IfNotPresent
  
service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: hello.local
      paths:
        - path: /hello
  tls: []
  
resources: 
   limits:
      cpu: 1000m
      memory: 2048Mi
   requests:
     cpu: 1000m
     memory: 2048Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

